# Generated by Django 3.1 on 2020-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200926_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='checked_number',
            field=models.IntegerField(default=0),
        ),
    ]
