# Generated by Django 3.1 on 2020-09-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_checked_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='max_number',
            field=models.IntegerField(default=30),
        ),
    ]
