# Generated by Django 3.1 on 2020-10-18 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_facilities_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='limit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='集合時間'),
        ),
    ]
