# Generated by Django 2.2.16 on 2020-10-18 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_facilities_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='limit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='集合時間'),
        ),
    ]
