# Generated by Django 2.2.16 on 2020-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20201018_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='store_area',
            field=models.CharField(max_length=255, null=True, verbose_name='地域'),
        ),
    ]
