# Generated by Django 3.1 on 2020-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_store_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.IntegerField(default=3000),
        ),
    ]
