# Generated by Django 3.1 on 2020-10-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='price',
            new_name='store_price',
        ),
    ]
