# Generated by Django 3.1 on 2020-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20201031_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(null=True, upload_to='img/upload'),
        ),
    ]
