# Generated by Django 3.1 on 2020-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20201031_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(null=True, upload_to='img/upload'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.ImageField(null=True, upload_to='img/upload'),
        ),
    ]
