# Generated by Django 3.1 on 2020-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20201031_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.URLField(blank=True, null=True, verbose_name='画像1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.URLField(blank=True, null=True, verbose_name='画像2'),
        ),
    ]
