# Generated by Django 3.1 on 2020-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20201104_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='checked_number',
            field=models.IntegerField(default=0, verbose_name='参加人数'),
        ),
    ]
